version: '3'

services:
    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/minhashoras
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm

    php-fpm:
        build: .
        volumes:
            - ./:/var/www/minhashoras
        environment:
            HOST_DB: ${POSTGRES_HOST}
            USER_DB: ${POSTGRES_USER}
            PASS_DB: ${POSTGRES_PASSWORD}
            NAME_DB: ${POSTGRES_DB}

    postgres:
        image: postgres:alpine
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
