version: '3'

services:
    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/minhashoras
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm

    php-fpm:
        image: php:7-fpm-alpine
        volumes:
            - ./:/var/www/minhashoras
